// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/resources/jflexDefinitions/Scanner.flex

package scanner;
import shared.models.TokenType;
import shared.models.Token;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class CodeScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int string_double_quote = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\22\0\1\4\1\0\1\5"+
    "\4\0\1\6\2\7\1\10\1\11\1\0\1\11\1\12"+
    "\1\13\1\14\11\15\7\0\13\16\1\17\16\16\1\0"+
    "\1\20\2\0\1\16\1\0\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\16\1\32\1\33"+
    "\1\16\1\34\1\35\1\36\1\16\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\16\1\46\1\7\1\16"+
    "\1\7\7\0\1\2\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\3\1\1\1\4\3\1\2\5"+
    "\22\6\1\7\1\10\1\11\3\0\1\12\1\0\1\2"+
    "\1\5\1\0\7\6\1\13\3\6\2\13\14\6\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\5\0\1\22\11\6"+
    "\1\13\20\6\1\23\1\24\1\25\1\26\1\0\1\12"+
    "\1\2\27\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\116\0\165\0\234\0\116\0\303"+
    "\0\116\0\352\0\u0111\0\u0138\0\u015f\0\u0186\0\u01ad\0\u01d4"+
    "\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be\0\u02e5\0\u030c"+
    "\0\u0333\0\u035a\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444"+
    "\0\u046b\0\116\0\u0492\0\u04b9\0\u04e0\0\u0111\0\u0507\0\u052e"+
    "\0\u0555\0\116\0\u057c\0\u05a3\0\u05ca\0\u05f1\0\u0618\0\u063f"+
    "\0\u0666\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\u01ad\0\u0750"+
    "\0\u0777\0\u079e\0\u07c5\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888"+
    "\0\u08af\0\u08d6\0\u08fd\0\u0924\0\116\0\116\0\116\0\116"+
    "\0\116\0\u094b\0\u0972\0\u0999\0\u09c0\0\u09e7\0\u0a0e\0\u057c"+
    "\0\u0a35\0\u0a5c\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8\0\u0b1f\0\u0b46"+
    "\0\u0b6d\0\u0b94\0\u0bbb\0\u0be2\0\u0c09\0\u0c30\0\u0c57\0\u0c7e"+
    "\0\u0ca5\0\u0ccc\0\u0cf3\0\u0d1a\0\u0d41\0\u0d68\0\u0d8f\0\u0db6"+
    "\0\u0ddd\0\u0e04\0\116\0\116\0\116\0\116\0\u0e2b\0\u0e2b"+
    "\0\u052e\0\u0e52\0\u0750\0\u0e79\0\u0ea0\0\u0ec7\0\u0eee\0\u0f15"+
    "\0\u0f3c\0\u0f63\0\u0f8a\0\u0fb1\0\u0fd8\0\u0fff\0\u1026\0\u104d"+
    "\0\u1074\0\u109b\0\u10c2\0\u10e9\0\u1110\0\u1137\0\u115e\0\u1185";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\3\1\5\1\6\1\7\1\10\1\11"+
    "\1\3\1\12\1\13\1\14\1\15\1\16\2\17\1\3"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\17"+
    "\1\27\1\17\1\30\1\31\1\17\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\2\17\1\41\1\0\1\41"+
    "\1\0\1\41\1\42\12\41\1\43\26\41\50\0\1\4"+
    "\51\0\1\6\42\0\1\44\3\0\14\44\1\45\26\44"+
    "\12\0\1\46\1\0\2\16\45\0\2\47\41\0\1\50"+
    "\2\0\1\51\45\0\1\47\1\0\2\16\1\0\1\52"+
    "\25\0\1\53\13\0\1\47\1\0\2\16\1\0\1\52"+
    "\43\0\4\17\1\0\26\17\14\0\4\17\1\0\21\17"+
    "\1\54\4\17\14\0\4\17\1\0\14\17\1\55\1\17"+
    "\1\56\7\17\14\0\4\17\1\0\1\57\6\17\1\60"+
    "\4\17\1\61\11\17\14\0\4\17\1\0\4\17\1\62"+
    "\7\17\1\63\11\17\14\0\4\17\1\0\12\17\1\57"+
    "\13\17\14\0\4\17\1\0\1\24\11\17\1\64\1\17"+
    "\1\65\4\17\1\66\4\17\14\0\4\17\1\0\14\17"+
    "\1\54\11\17\14\0\4\17\1\0\5\17\1\67\5\17"+
    "\1\70\12\17\14\0\4\17\1\0\14\17\1\71\11\17"+
    "\14\0\4\17\1\0\4\17\1\72\21\17\14\0\4\17"+
    "\1\0\16\17\1\73\7\17\14\0\4\17\1\0\4\17"+
    "\1\74\21\17\14\0\4\17\1\0\7\17\1\75\1\76"+
    "\7\17\1\77\2\17\1\100\2\17\14\0\4\17\1\0"+
    "\16\17\1\101\7\17\14\0\4\17\1\0\13\17\1\102"+
    "\12\17\14\0\4\17\1\0\14\17\1\103\11\17\14\0"+
    "\4\17\1\0\7\17\1\104\16\17\1\41\1\0\1\41"+
    "\1\0\1\41\1\0\12\41\1\0\26\41\5\0\1\105"+
    "\26\0\1\106\2\0\1\107\1\0\1\110\13\0\1\111"+
    "\46\0\1\112\25\0\1\113\2\0\1\114\1\0\1\115"+
    "\21\0\2\47\7\0\1\116\21\0\2\50\1\0\5\50"+
    "\1\117\36\50\1\51\3\0\43\51\14\0\2\120\45\0"+
    "\4\17\1\0\20\17\1\121\5\17\14\0\4\17\1\0"+
    "\14\17\1\122\11\17\14\0\4\17\1\0\4\17\1\123"+
    "\21\17\14\0\4\17\1\0\17\17\1\124\6\17\14\0"+
    "\4\17\1\0\1\125\25\17\14\0\4\17\1\0\13\17"+
    "\1\126\12\17\14\0\4\17\1\0\5\17\1\127\20\17"+
    "\14\0\4\17\1\0\21\17\1\130\4\17\14\0\4\17"+
    "\1\0\14\17\1\131\11\17\14\0\4\17\1\0\16\17"+
    "\1\132\7\17\14\0\4\17\1\0\13\17\1\133\12\17"+
    "\14\0\4\17\1\0\20\17\1\67\5\17\14\0\4\17"+
    "\1\0\13\17\1\134\12\17\14\0\4\17\1\0\23\17"+
    "\1\67\2\17\14\0\4\17\1\0\10\17\1\135\15\17"+
    "\14\0\4\17\1\0\2\17\1\136\12\17\1\137\2\17"+
    "\1\140\5\17\14\0\4\17\1\0\14\17\1\141\11\17"+
    "\14\0\4\17\1\0\6\17\1\142\16\17\1\143\14\0"+
    "\4\17\1\0\1\144\15\17\1\145\7\17\14\0\4\17"+
    "\1\0\10\17\1\146\15\17\14\0\4\17\1\0\21\17"+
    "\1\124\4\17\14\0\4\17\1\0\20\17\1\147\5\17"+
    "\14\0\4\17\1\0\10\17\1\150\1\17\1\151\13\17"+
    "\14\0\4\17\1\0\10\17\1\152\15\17\6\0\1\153"+
    "\46\0\1\154\46\0\1\155\46\0\1\156\51\0\1\157"+
    "\2\0\2\160\31\0\2\50\1\0\5\50\1\117\2\50"+
    "\1\161\33\50\14\0\4\17\1\0\14\17\1\67\11\17"+
    "\14\0\4\17\1\0\12\17\1\67\13\17\14\0\4\17"+
    "\1\0\1\162\25\17\14\0\4\17\1\0\4\17\1\67"+
    "\21\17\14\0\4\17\1\0\16\17\1\67\7\17\14\0"+
    "\4\17\1\0\17\17\1\163\1\164\5\17\14\0\4\17"+
    "\1\0\1\165\25\17\14\0\4\17\1\0\1\17\1\152"+
    "\24\17\14\0\4\17\1\0\1\163\25\17\14\0\4\17"+
    "\1\0\4\17\1\166\21\17\14\0\4\17\1\0\2\17"+
    "\1\167\23\17\14\0\4\17\1\0\6\17\1\67\17\17"+
    "\14\0\4\17\1\0\13\17\1\170\12\17\14\0\4\17"+
    "\1\0\14\17\1\171\11\17\14\0\4\17\1\0\4\17"+
    "\1\131\21\17\14\0\4\17\1\0\21\17\1\172\4\17"+
    "\14\0\4\17\1\0\16\17\1\163\7\17\14\0\4\17"+
    "\1\0\13\17\1\173\12\17\14\0\4\17\1\0\4\17"+
    "\1\174\21\17\14\0\4\17\1\0\16\17\1\163\1\17"+
    "\1\175\5\17\14\0\4\17\1\0\10\17\1\71\15\17"+
    "\14\0\4\17\1\0\20\17\1\176\5\17\14\0\4\17"+
    "\1\0\10\17\1\122\15\17\14\0\4\17\1\0\3\17"+
    "\1\67\22\17\14\0\4\17\1\0\1\177\25\17\14\0"+
    "\4\17\1\0\12\17\1\124\13\17\14\0\2\160\45\0"+
    "\4\17\1\0\11\17\1\67\14\17\14\0\4\17\1\0"+
    "\10\17\1\200\15\17\14\0\4\17\1\0\21\17\1\201"+
    "\4\17\14\0\4\17\1\0\1\176\25\17\14\0\4\17"+
    "\1\0\20\17\1\202\5\17\14\0\4\17\1\0\20\17"+
    "\1\203\5\17\14\0\4\17\1\0\16\17\1\150\7\17"+
    "\14\0\4\17\1\0\16\17\1\204\7\17\14\0\4\17"+
    "\1\0\4\17\1\150\21\17\14\0\4\17\1\0\14\17"+
    "\1\205\11\17\14\0\4\17\1\0\10\17\1\206\15\17"+
    "\14\0\4\17\1\0\2\17\1\207\23\17\14\0\4\17"+
    "\1\0\20\17\1\104\5\17\14\0\4\17\1\0\13\17"+
    "\1\101\12\17\14\0\4\17\1\0\12\17\1\163\13\17"+
    "\14\0\4\17\1\0\10\17\1\210\15\17\14\0\4\17"+
    "\1\0\12\17\1\204\13\17\14\0\4\17\1\0\13\17"+
    "\1\67\12\17\14\0\4\17\1\0\5\17\1\67\20\17"+
    "\14\0\4\17\1\0\2\17\1\67\23\17\14\0\4\17"+
    "\1\0\7\17\1\67\16\17\14\0\4\17\1\0\14\17"+
    "\1\204\11\17";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4524];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\1\1\1\11\30\1\1\11"+
    "\1\1\3\0\1\1\1\0\1\1\1\11\1\0\31\1"+
    "\5\11\1\1\5\0\33\1\4\11\1\0\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    LiteralParser literalParser = LiteralParser.getInstance();
    StringBuilder sb = new StringBuilder();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public CodeScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token getNext() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return Token.of(null, TokenType.EOF, yyline, yycolumn);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error(String.format("Illegal character <%s> at line: %d column: %d", yytext(), yyline, yycolumn));
            }
            // fall through
          case 23: break;
          case 2:
            { 
            }
            // fall through
          case 24: break;
          case 3:
            { yybegin(string_double_quote); sb.setLength(0);
            }
            // fall through
          case 25: break;
          case 4:
            { return Token.of(yytext(), TokenType.ETC, yyline, yycolumn);
            }
            // fall through
          case 26: break;
          case 5:
            { return Token.of(literalParser.parseDecimal(yytext()), TokenType.INTEGER_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 6:
            { return Token.of(yytext(), TokenType.IDENTIFIER, yyline, yycolumn);
            }
            // fall through
          case 28: break;
          case 7:
            { sb.append(yytext());
            }
            // fall through
          case 29: break;
          case 8:
            { yybegin(YYINITIAL); return Token.of(sb.toString(), TokenType.STRING_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 30: break;
          case 9:
            { sb.append('\\');
            }
            // fall through
          case 31: break;
          case 10:
            { return Token.of(literalParser.parseFloat(yytext()), TokenType.FLOAT_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 11:
            { return Token.of(yytext(), TokenType.KEYWORD, yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 12:
            { sb.append('\"');
            }
            // fall through
          case 34: break;
          case 13:
            { sb.append('\n');
            }
            // fall through
          case 35: break;
          case 14:
            { sb.append('\r');
            }
            // fall through
          case 36: break;
          case 15:
            { sb.append('\t');
            }
            // fall through
          case 37: break;
          case 16:
            { return Token.of(yytext().charAt(1), TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 38: break;
          case 17:
            { return Token.of('\\', TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 39: break;
          case 18:
            { return Token.of(literalParser.parseHexInt(yytext()), TokenType.INTEGER_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 40: break;
          case 19:
            { return Token.of('\'', TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 41: break;
          case 20:
            { return Token.of('\n', TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 42: break;
          case 21:
            { return Token.of('\r', TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 43: break;
          case 22:
            { return Token.of('\t', TokenType.CHAR_LITERAL, yyline, yycolumn);
            }
            // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
